services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    #volumes:
    # - .:/app
    restart: on-failure
    depends_on:
      - database
      - rabbitmq

  web-proxy:
    build: ./web-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  database:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  rabbitmq_data:
  db_data:
