version: '3.8'

services:
  # Frontend
  frontend:
    build:
      context: ./frontend_prod
    volumes:
      - ./frontend_prod:/src
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - BACKEND_API_URL=http://app:8080
      - PYTHONUNBUFFERED=1
    depends_on:
      - app
    restart: on-failure

  # Application
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/src/app
    command: uvicorn app.api:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=database
      - RABBITMQ_HOST=rabbitmq
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/src
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  # ML-workers
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - ./worker:/worker_app
      - ./app:/shared/app:ro
    deploy:
      replicas: 2
    env_file:
      - .env
    environment:
      - DB_HOST=database
      - RABBITMQ_HOST=rabbitmq
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/shared
    restart: always
    depends_on:
      - database
      - rabbitmq

  # DB-Service
  init-db:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/src/app
    command: python -m app.main
    env_file:
      - .env
    environment:
      - DB_HOST=database
      - PYTHONPATH=/src
    depends_on:
      database:
        condition: service_healthy
    restart: "no"

  # Proxy (Nginx)
  web-proxy:
    build: ./web-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always

  # Message Broker
  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692" # Метрики доступны здесь
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  # PostgreSQL
  database:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - rabbitmq
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # Быстрый Вход для Viewer, без регистрации 
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    restart: always
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  # Сервис нагрузочного тестирования
  k6:
    image: grafana/k6:latest
    volumes:
      - ./tests:/scripts
    entrypoint: ["k6"]
    network_mode: "host"

volumes:
  rabbitmq_data:
  db_data:
  prometheus_data:
  grafana_data: